/*
 * Dump every spoken line in the app into docs/PHRASES_REVIEW.md so the wording can
 * be reviewed/improved in one place. Pure read — generates a Markdown report.
 *   node scripts/list-phrases.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { WORLDS } from '../src/data/content.js'
import { WORDS, PHRASES, CATEGORIES, wordsInCategory } from '../src/data/phraseContent.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, '..', 'docs', 'PHRASES_REVIEW.md')

const L = []
const w = (s = '') => L.push(s)

w('# Phrases Review')
w('')
w('> Every spoken line in the app, grouped by source, so wording can be improved in one pass.')
w('> Generated by `scripts/list-phrases.mjs` — edit the source files, then re-run to refresh.')
w('')

// ---- Learning worlds: the word, its spoken line, and the expand ladder ----
w('## Learning worlds')
w('Source: `src/data/content.js` (each item `say` + `expand`).')
for (const world of WORLDS) {
  w('')
  w(`### ${world.name} — \`${world.id}\` (${world.items.length})`)
  for (const it of world.items) {
    const say = it.say || (it.soundLabel ? `(sound: ${it.soundLabel})` : '')
    w(`- **${it.word}** — "${say}"`)
    if (it.expand?.length) w(`  - ladder: ${it.expand.map((p) => `"${p}"`).join(' · ')}`)
  }
}

// ---- Game prompts (kept in sync with gen-phrases.mjs) ----
w('')
w('## Game prompts')
w('Source: `SoundGame` / `TwinMode` / `ChoiceGame` templates (mirrored in `scripts/gen-phrases.mjs`).')
const POOL_IDS = ['safari-island', 'things-i-do', 'my-body', 'home-village']
for (const world of WORLDS) {
  if (!POOL_IDS.includes(world.id)) continue
  for (const it of world.items) {
    if (it.portrait) continue
    const wd = it.word.toLowerCase()
    const prompts = it.soundLabel
      ? [`Listen… ${it.soundLabel}! Where is the ${wd}?`, `find the ${wd} — listen, ${it.soundLabel}!`]
      : [`Can you find the ${wd}?`, `find the ${wd}!`]
    prompts.push(`Yes! ${it.word}!`, `Try again. Find the ${wd}.`)
    w(`- ${it.word}: ${prompts.map((p) => `"${p}"`).join(' · ')}`)
  }
}

// ---- Speech-therapy vocabulary (Word Practice / Phrase Builder / Word Board) ----
w('')
w('## Speech-therapy vocabulary')
w('Source: `src/data/phraseContent.js`.')
w('')
w(`### Single words (${WORDS.length}) — by category`)
for (const cat of CATEGORIES) {
  w(`- **${cat}**: ${wordsInCategory(cat).map((x) => x.word).join(', ')}`)
}
w('')
w(`### Two-word phrases (${PHRASES[2].length})`)
w(PHRASES[2].map((p) => `"${p.phrase}"`).join(' · '))
w('')
w(`### Three-word phrases (${PHRASES[3].length})`)
w(PHRASES[3].map((p) => `"${p.phrase}"`).join(' · '))
w('')

writeFileSync(OUT, L.join('\n'))
console.log(`Wrote ${OUT} (${L.length} lines).`)
